### ISSUE TITLE
"Adjust disc usage" is too pessimistic, creating smaller ISOs than it says it will

### ISSUE THREAD

**Issue by qazwsxedcgit** [rastersoft/devedeng#42]
Clicking on "adjust disc usage" when, for example, using a 4.7GB DVD media, results in the "usage" bar between the media size dropdown and the "Adjust disc usage" button going to 99%.

Expected behaviour: DevedeNG adjusts bitrates of files being converted so that the resulting ISO fills up 99% of the media, i.e. at least 4.65GB in this example, and 99% of other media sizes, too.

Actual behaviour: DevedeNG creates a 3.7GB ISO, even from sources that resulted initially in a figure of more than 100% being displayed in the usage bar. As a result of the bit rates being set too low, image quality suffers.

**Comment by rastersoft** [comment]
Unfortunately it is not easy to do a good prediction. Currently I take the desired bitrate and multiply it by the duration of the clip. That should be the final size, but, for some reason, the final size is quite smaller, but in an unpredictable way :(

**Comment by Juniorsnet** [comment]
The problem is in two places.

1.- The disc size reported in get_dvd_size() is 4200.0 MB and must be 4489.0 MB (4.700.372.992 /1024 /1024)(Wikipedia DVD sizes).

2.- This is the important problem, in case of FFMPEG, when is used the option -target ntsc-dvd or pal-dvd, ignores de bitrate aplied by devede and FFMPEG simply uses de default quality value "-q 2" wich is bad and encodes at low bit rate.

Ref:

http://todayiwantedtoprogram.tumblr.com/post/15142587796/what-does-ffmpegs-target-pal-dvd-actually-do

The solution is not use the -target ntsc-dvd or pal-dvd and put all option in the comandline so FFMPEG take the correct bitrate by devede.

**Comment by rastersoft** [comment]
Thanks.

First, I slightly decreased the size to take into account other disk structures.

About the point 2, first I have to say... THANKS!!!! Finally an explanation to why the final size was so different to the predicted one.

I'll check it.

**Comment by rastersoft** [comment]
Just a question: does AVConv work the same?

**Comment by Juniorsnet** [comment]
Yes, work in the same way, at least with avconv 9.18

**Comment by rastersoft** [comment]
Ok, I just uploaded to master version 4.8.3, which should fix this for all formats (DVD, VCD, SVCD and CVD). Could you check it, before uploading the .deb and .rpm packages?

**Comment by Juniorsnet** [comment]
It does not work, because needed adjust maxrate and minrate with the same value as -b:v which is calculated by DeVeDe.

In the first test the file is encoded at ~2 Mbit even with -b:v 9000k (calculated by DeVeDe)

[DevedeCreateDVD_bad.txt](https://github.com/rastersoft/devedeng/files/534440/DevedeCreateDVD_bad.txt)

In the second the file is encoded at 9 Mbit (calculated by DeVeDe)

I edited the source a little to get the correct comandline.

[DevedeCreateDVD_ok.txt](https://github.com/rastersoft/devedeng/files/534449/DevedeCreateDVD_ok.txt)

(Y)

**Comment by rastersoft** [comment]
Hi again:

Try now. I dislike the idea of setting both minimum and maximum to the same value, because in MPEG the I frames need much more disc space than the P or B frames. I modified the code to set the minimum to  2/3 of the average, and the maximum to 1.5 times the average. Also fixed the commands (now uses "minrate:v" and "maxrate:v" instead of "minrate" and "maxrate"). Try now, please.

**Comment by Juniorsnet** [comment]
This work much better, although ffmpeg likes more the minrate than de average, but ~6Mbit vs ~2Mbit is a lot better.

[DevedeCreateDVD_470.txt](https://github.com/rastersoft/devedeng/files/535137/DevedeCreateDVD_470.txt)

**Comment by rastersoft** [comment]
Take into account that an already-compressed file is not a good source...

**Comment by Juniorsnet** [comment]
Indeed, but in my intel atom netbook can't encode too long file. But in my office test a large file from a handycam.

[DeVeDeNG_test.txt](https://github.com/rastersoft/devedeng/files/536663/DeVeDeNG_test.txt)

**Comment by qazwsxedcgit** [comment]
Tried 4.8.3, Debian package. Still creates only 3.3GB .iso when I ask for a 4.7GB DVD to be filled by clicking "Adjust disc usage". If there's some log or debug output that would help, please say how to generate it and I'll run this again.

**Comment by Juniorsnet** [comment]
This is because the author set the minimun rate at 2/3 from the caculated bitrate (4.7 GB in your case) then the dvd created is (4.7 \* 0.666666...) aprox.

**Comment by Juniorsnet** [comment]
Has aditional data the program dvdstyler put the minrate and the maxrate at same value.
however the maxrate limit is not 9Mbit, is 8Mbit maybe to allow margin for the I frames.

**Comment by rastersoft** [comment]
If the source is an already-compressed video, then it is logic that the final bitrate is equal to the minimum, because all the information that could be removed has already been removed. But if you start with a big-bitrate source, then the final video will have a bitrate much more similar to the desired one.
