### ISSUE TITLE
DevedeNG creates undersized DVD .iso image

### ISSUE THREAD

**Issue by sthenc** [rastersoft/devedeng#7]
Hi.

I just installed the package on lubuntu 14.04 (from http://www.rastersoft.com/descargas/python3-devedeng-jessie_4.0-debian2_all.deb), but I am having some problems:

I am fitting a lot of video on one dvd disk, so I have to press "Adjust disk usage" for the disk usage
to be under 100%.
Everything works, and it creates a working .iso image but it is only 3.5 GB instead of >4GB.

I assume the code that calculates the needed bitrate or disk usage is too cautious.
I was looking at the code but I can't find which part does that calculation.

**Comment by glenntanner3** [comment]
I personally have not looked at this section of code before, but it looks like it located in project.py 'def on_adjust_disc_usage_clicked(self,b):'

**Comment by rastersoft** [comment]
Unfortunately, calculating the final size is very tricky: I can set a bitrate, but it is possible that AVConv, FFMpeg or Mencoder will use less, because the original video is very compressible and can be compressed with the same quality using an smaller bitrate.

Of course, I'm open to ideas to fix this.
